server.servlet.context-path=/
spring.datasource.url=jdbc:h2:mem:eamlightdb;DB_CLOSE_DELAY=-1;MODE=Oracle
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.hbm2ddl.auto=create-only
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Permit all local requests without Spring Security authentication prompts
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration,org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
